Fix dependency error with ShapeInferencePass (#685)
A compile order dependency issue was introduced with commit
09259975200307925971b4cd51061d942f794868

In file included from /build/third_party/onnx-mlir/src/Dialect/ONNX/ONNXOps.hpp:27,
                 from /build/third_party/onnx-mlir/src/Transform/ONNX/ShapeInferencePass.cpp:23:
/build/third_party/onnx-mlir/src/Interface/HasOnnxSubgraphOpInterface.hpp:26:10: fatal error: src/Interface/HasOnnxSubgraphOpInterface.hpp.inc: No such file or directory
 #include "src/Interface/HasOnnxSubgraphOpInterface.hpp.inc"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Steven Royer <seroyer@us.ibm.com>